version: 2.1
jobs:
  test:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run:
          name: Clean and install
          command: mvn clean install
      - run:
          name: Test
          command: mvn test
      - run:
          name: Generate allure report
          command: mvn allure:report
      - store_test_results:
          path: target/surefire-reports/junitreports
      - store_artifacts:
          path: target/site/allure-maven-plugin/

workflows:
  commit:
    jobs:
      - test
